# Generated by Django 5.2.3 on 2026-09-29 19:38

import classroom_engine.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_engine', '0002_selector_lanzamiento_dispositivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucion',
            name='estudio_hasta',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='pausada_ms',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='puntos_totales',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='distribucion',
            name='total_preguntas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participante',
            name='ayuda_en',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='proyectado_desde',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='proyectado_por',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='resumen',
            name='detalle',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='sesiondeclase',
            name='anclajes',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Intento',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('persona_id', models.CharField(max_length=64)),
                ('numero', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('en_curso', 'en_curso'), ('entregado', 'entregado'), ('pendiente_decision', 'pendiente_decision'), ('descartado', 'descartado')], default='en_curso', max_length=20)),
                ('iniciado_en', models.BigIntegerField(default=classroom_engine.models.ahora_ms)),
                ('enviado_en', models.BigIntegerField(blank=True, null=True)),
                ('capturado_en', models.BigIntegerField(blank=True, null=True)),
                ('puntaje', models.FloatField(blank=True, null=True)),
                ('puntaje_maximo', models.FloatField(blank=True, null=True)),
                ('respuestas', models.JSONField(default=list)),
                ('origen_envio', models.CharField(default='directo', max_length=16)),
                ('recuperado_de_cola', models.BooleanField(default=False)),
                ('dispositivo_id', models.CharField(blank=True, default='', max_length=36)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='classroom_engine.distribucion')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='classroom_engine.participante')),
            ],
            options={
                'db_table': 'm07_intento',
                'indexes': [models.Index(fields=['distribucion', 'estado'], name='ix_m07_intento_dist')],
                'constraints': [models.UniqueConstraint(fields=('distribucion', 'participante', 'numero'), name='ux_m07_intento_numero'), models.UniqueConstraint(condition=models.Q(('estado', 'en_curso')), fields=('distribucion', 'participante'), name='ux_m07_intento_en_curso'), models.CheckConstraint(condition=models.Q(('enviado_en__isnull', True), ('enviado_en__gte', models.F('iniciado_en')), _connector='OR'), name='ck_m07_intento_envio_posterior')],
            },
        ),
    ]
