# Generated by Django 5.2.3 on 2026-09-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_manager', '0002_organizacion_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='bateria_pct',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='espacio_libre_mb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
