# Generated by Django 5.2.3 on 2026-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0009_permisos_evaluacion'),
        ('device_manager', '0004_perfil_y_dueno_del_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='capacidad_control',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='capacidad_declarada_en',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='capacidad_detalle',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.CheckConstraint(condition=models.Q(('capacidad_control__in', ('', 'abierto', 'supervisado', 'controlado'))), name='ck_m09_dispositivo_capacidad_valida'),
        ),
    ]
