# Generated by Django 5.2.3 on 2026-10-06 14:27

import acceso.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso', '0009_permisos_evaluacion'),
        ('device_manager', '0005_capacidad_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinMaestro',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=255)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.BigIntegerField(default=acceso.models.ahora_ms)),
                ('vence_en', models.BigIntegerField()),
                ('sustituida_en', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'm01_pin_maestro',
            },
        ),
        migrations.AddField(
            model_name='organizacion',
            name='visitante',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='politicacredencial',
            name='autoregistro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='politicacredencial',
            name='bloqueo_alcance',
            field=models.CharField(default='CUENTA', max_length=12),
        ),
        migrations.AddField(
            model_name='usuario',
            name='confirmado_en',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='origen',
            field=models.CharField(default='INSTALACION', max_length=16),
        ),
        migrations.AddIndex(
            model_name='intentoacceso',
            index=models.Index(fields=['dispositivo', '-momento'], name='m01_intento_disposi_9a8167_idx'),
        ),
        migrations.AddIndex(
            model_name='intentoacceso',
            index=models.Index(fields=['motivo', '-momento'], name='m01_intento_motivo_29a92d_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['organizacion', 'origen'], name='m01_usuario_organiz_9fcd6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='politicacredencial',
            constraint=models.CheckConstraint(condition=models.Q(('bloqueo_alcance__in', ['CUENTA', 'DISPOSITIVO'])), name='ck_m01_politica_bloqueo_alcance'),
        ),
        migrations.AddField(
            model_name='pinmaestro',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='acceso.usuario'),
        ),
        migrations.AddField(
            model_name='pinmaestro',
            name='organizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pines_maestros', to='acceso.organizacion'),
        ),
        migrations.AddIndex(
            model_name='pinmaestro',
            index=models.Index(fields=['organizacion', '-creado_en'], name='m01_pin_mae_organiz_e3a266_idx'),
        ),
        migrations.AddConstraint(
            model_name='pinmaestro',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('organizacion',), name='uq_m01_pin_maestro_activo'),
        ),
        migrations.AddConstraint(
            model_name='pinmaestro',
            constraint=models.CheckConstraint(condition=models.Q(('activa', True), ('sustituida_en__isnull', False), _connector='OR'), name='ck_m01_pin_maestro_sustitucion'),
        ),
        migrations.AddConstraint(
            model_name='pinmaestro',
            constraint=models.CheckConstraint(condition=models.Q(('vence_en__gt', models.F('creado_en'))), name='ck_m01_pin_maestro_vigencia'),
        ),
    ]
