# Generated by Django 5.2.3 on 2026-10-08 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=64, unique=True)),
                ('fuente', models.CharField(max_length=16)),
                ('curso_ref', models.CharField(max_length=200)),
                ('curso_version', models.CharField(blank=True, default='', max_length=32)),
                ('media_ref', models.CharField(max_length=200)),
                ('ruta', models.CharField(blank=True, default='', max_length=500)),
                ('estado', models.CharField(choices=[('pendiente', 'pendiente'), ('descargando', 'descargando'), ('disponible', 'disponible'), ('fallido', 'fallido'), ('cancelado', 'cancelado')], default='pendiente', max_length=12)),
                ('prioridad', models.SmallIntegerField(default=2)),
                ('tipo_mime', models.CharField(blank=True, default='', max_length=200)),
                ('bytes_total', models.BigIntegerField(blank=True, null=True)),
                ('bytes_hechos', models.BigIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('cabeceras', models.JSONField(default=dict)),
                ('intentos', models.IntegerField(default=0)),
                ('error_codigo', models.CharField(blank=True, default='', max_length=40)),
                ('error_detalle', models.CharField(blank=True, default='', max_length=500)),
                ('reintentar_despues', models.BigIntegerField(blank=True, null=True)),
                ('usos', models.BigIntegerField(default=0)),
                ('creado_en', models.BigIntegerField()),
                ('actualizado_en', models.BigIntegerField()),
                ('iniciado_en', models.BigIntegerField(blank=True, null=True)),
                ('terminado_en', models.BigIntegerField(blank=True, null=True)),
                ('validado_en', models.BigIntegerField(blank=True, null=True)),
                ('ultimo_uso_en', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cm_recurso',
                'indexes': [models.Index(fields=['estado', 'prioridad'], name='cm_recurso_cola'), models.Index(fields=['curso_ref', 'media_ref'], name='cm_recurso_medio'), models.Index(fields=['ultimo_uso_en'], name='cm_recurso_uso')],
                'constraints': [models.CheckConstraint(condition=models.Q(('estado__in', ('pendiente', 'descargando', 'disponible', 'fallido', 'cancelado'))), name='cm_recurso_estado_valido'), models.CheckConstraint(condition=models.Q(('bytes_hechos__gte', 0)), name='cm_recurso_bytes_hechos_no_negativos')],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('modulo', models.CharField(choices=[('aula', 'aula'), ('estudio', 'estudio'), ('evaluacion', 'evaluacion')], max_length=12)),
                ('contexto_ref', models.CharField(blank=True, default='', max_length=64)),
                ('prioridad', models.SmallIntegerField(default=2)),
                ('persona_id', models.CharField(blank=True, default='', max_length=64)),
                ('dispositivo_id', models.CharField(blank=True, default='', max_length=64)),
                ('creada_en', models.BigIntegerField()),
                ('vence_en', models.BigIntegerField(blank=True, null=True)),
                ('recurso', models.ForeignKey(db_column='recurso_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='cola_medios.recurso')),
            ],
            options={
                'db_table': 'cm_solicitud',
                'indexes': [models.Index(fields=['modulo', 'contexto_ref'], name='cm_solicitud_contexto')],
                'constraints': [models.CheckConstraint(condition=models.Q(('modulo__in', ('aula', 'estudio', 'evaluacion'))), name='cm_solicitud_modulo_valido'), models.UniqueConstraint(fields=('recurso', 'modulo', 'contexto_ref', 'persona_id'), name='cm_solicitud_unica')],
            },
        ),
    ]
